name: setupAndTest
on: push
jobs:
  setupAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        cache: npm
    - name: using, test and linter
    - run: make setup
    - run: make test
    - run: make lint
        
        

